version: '3'
services:
  web:
    build: .
    ports:
      - '5001:5001'
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-CU12-ubuntu-20.04
    user: root
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: 'Password12345678!'
      ACCEPT_EULA: 'Y'
    volumes:
      - db:/var/opt/mssql/data

volumes:
  db:
