version: '3'
services:
  beekeeper:
    build: .
    ports:
      - '5000:80'
      - '5001:443'
    environment:
      ConnectionStrings__DefaultConnection: "server=localhost;database=beekeeper;user=root;password='';"
      Crypto__Iv: '<16 chars long>'
      Crypto__Key: '<CRYPTO KEY>'
      JWT__Secret: '<JWT SECRET>'
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
