name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
  build_frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install global deps
        run: |
          npm install -g @angular/cli
      - name: Install project dependencies
        run: cd Beekeeper.Frontend && npm install
      - name: Openapi
        run: cd Beekeeper.Frontend && npm run openapi:generate
      - name: Lint project
        run: cd Beekeeper.Frontend && ng lint
      - name: Build project
        run: cd Beekeeper.Frontend && ng build
